@startuml
top to bottom direction
package entity {
    class card
    class formatted_text
    class image
    class style
}

package usecase {
    class export
    class generate
}

package InterfaceAdapter{
    class a_image
    interface generate_interface
    class a_export
    interface export_interface
    class a_card
    interface decoder_interface
}

package driver {
    class d_image
    class d_export
    class d_csv_decoder
}

generate -up-> card
generate -up-> formatted_text
generate -up-> image
generate -up-> style
export   -up-> card
export   -up-> formatted_text
export   -up-> image
export   -up-> style
a_image .up.> image
a_export .up.> image
a_card .up.> card
a_image -down-> generate_interface
a_export -down-> export_interface
a_card -down-> decoder_interface
d_image -down-> generate_interface
d_export -up-> export_interface
d_csv_decoder -up-> decoder_interface

@enduml