@startuml
top to bottom direction
package entity {
    class card
    class formatted_text
    class image
    class style
}

package usecase {
    class generate
    class generate_interface
}

package InterfaceAdapter{
    class image
    class layout
    class decoder
    class decoder_interface
}

package Details {
    class import
    class export
}

generate .up.> card
generate .up.> formatted_text
generate .up.> image
generate .up.> style
layout -up-> generate_interface
decoder -up-> generate_interface
decoder -down-> decoder_interface
import -up-> decoder_interface
export -up-> decoder_interface
@enduml